---
abstract: 'Perform an RFC 4533 LDAP sync'
author:
  - 'Ben Morrow <ben@morrow.me.uk>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-LDAPx-Sync
provides:
  Net::LDAPx::Sync:
    file: lib/Net/LDAPx/Sync.pm
requires:
  Carp: '0'
  Data::UUID: '0'
  Moo: '0'
  MooX::Role::WeakClosure: '0'
  Net::LDAP: '0'
  Try::Tiny: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-LDAPx-Sync
  license: http://opensource.org/licenses/bsd-license.php
  repository: http://github.com/mauzo/Net-LDAPx-Sync
version: '0'
